// AUTO-GENERATED by tools/extract_av1_cdef/harness.c — dav1d reference.
// (best_dir, var) for each 8×8 input.
static CDEF_DIR_REF: &[(i32, u32)] = &[
    (0, 0), // flat=128
    (6, 186322), // horizontal-ramp
    (2, 186322), // vertical-ramp
    (0, 108045), // diag TL->BR
    (4, 108045), // anti-diag TR->BL
    (7, 45438), // alt shallow
    (0, 0), // checkerboard
    (4, 37721), // lcg-noise
];
