/* Reference generator for the dav1d AV1 CDEF direction search (BSD-2-Clause).
 * Runs the real `cdef_find_dir_c` on known 8×8 blocks and dumps each
 * (best_dir, var) result as Rust literals to validate the Rust transcription
 * bit-for-bit. dav1d src/cdef_tmpl.c. Dev-time only. */
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

typedef uint8_t pixel;
#define PXSTRIDE(s) (s)
static inline int imin(int a, int b) { return a < b ? a : b; }
static inline int imax(int a, int b) { return a > b ? a : b; }
static int bitdepth_from_max(int m) { (void) m; return 8; }
#define bitdepth_max 255

/* ---- verbatim from dav1d src/cdef_tmpl.c (cdef_find_dir_c) ---- */
static int cdef_find_dir_c(const pixel *img, const ptrdiff_t stride,
                           unsigned *const var)
{
    const int bitdepth_min_8 = bitdepth_from_max(bitdepth_max) - 8;
    int partial_sum_hv[2][8] = { { 0 } };
    int partial_sum_diag[2][15] = { { 0 } };
    int partial_sum_alt[4][11] = { { 0 } };

    for (int y = 0; y < 8; y++) {
        for (int x = 0; x < 8; x++) {
            const int px = (img[x] >> bitdepth_min_8) - 128;

            partial_sum_diag[0][     y       +  x      ] += px;
            partial_sum_alt [0][     y       + (x >> 1)] += px;
            partial_sum_hv  [0][     y                 ] += px;
            partial_sum_alt [1][3 +  y       - (x >> 1)] += px;
            partial_sum_diag[1][7 +  y       -  x      ] += px;
            partial_sum_alt [2][3 - (y >> 1) +  x      ] += px;
            partial_sum_hv  [1][                x      ] += px;
            partial_sum_alt [3][    (y >> 1) +  x      ] += px;
        }
        img += PXSTRIDE(stride);
    }

    unsigned cost[8] = { 0 };
    for (int n = 0; n < 8; n++) {
        cost[2] += partial_sum_hv[0][n] * partial_sum_hv[0][n];
        cost[6] += partial_sum_hv[1][n] * partial_sum_hv[1][n];
    }
    cost[2] *= 105;
    cost[6] *= 105;

    static const uint16_t div_table[7] = { 840, 420, 280, 210, 168, 140, 120 };
    for (int n = 0; n < 7; n++) {
        const int d = div_table[n];
        cost[0] += (partial_sum_diag[0][n]      * partial_sum_diag[0][n] +
                    partial_sum_diag[0][14 - n] * partial_sum_diag[0][14 - n]) * d;
        cost[4] += (partial_sum_diag[1][n]      * partial_sum_diag[1][n] +
                    partial_sum_diag[1][14 - n] * partial_sum_diag[1][14 - n]) * d;
    }
    cost[0] += partial_sum_diag[0][7] * partial_sum_diag[0][7] * 105;
    cost[4] += partial_sum_diag[1][7] * partial_sum_diag[1][7] * 105;

    for (int n = 0; n < 4; n++) {
        unsigned *const cost_ptr = &cost[n * 2 + 1];
        for (int m = 0; m < 5; m++)
            *cost_ptr += partial_sum_alt[n][3 + m] * partial_sum_alt[n][3 + m];
        *cost_ptr *= 105;
        for (int m = 0; m < 3; m++) {
            const int d = div_table[2 * m + 1];
            *cost_ptr += (partial_sum_alt[n][m]      * partial_sum_alt[n][m] +
                          partial_sum_alt[n][10 - m] * partial_sum_alt[n][10 - m]) * d;
        }
    }

    int best_dir = 0;
    unsigned best_cost = cost[0];
    for (int n = 1; n < 8; n++) {
        if (cost[n] > best_cost) {
            best_cost = cost[n];
            best_dir = n;
        }
    }

    *var = (best_cost - (cost[best_dir ^ 4])) >> 10;
    return best_dir;
}
/* ---- end verbatim ---- */

int main(void) {
    /* 8 deterministic 8×8 blocks exercising every dominant direction plus flat
     * and noisy inputs. Builders are pure integer functions (no RNG). */
    pixel blocks[8][64];
    const char *names[8] = {
        "flat=128", "horizontal-ramp", "vertical-ramp", "diag TL->BR",
        "anti-diag TR->BL", "alt shallow", "checkerboard", "lcg-noise",
    };
    for (int i = 0; i < 64; i++) blocks[0][i] = 128;
    for (int y = 0; y < 8; y++) for (int x = 0; x < 8; x++) {
        blocks[1][y*8+x] = (pixel)(20 + x * 26);           // horizontal gradient
        blocks[2][y*8+x] = (pixel)(20 + y * 26);           // vertical gradient
        blocks[3][y*8+x] = (pixel)(20 + ((x+y) * 14));     // main diagonal
        blocks[4][y*8+x] = (pixel)(20 + ((x + (7-y)) * 14)); // anti-diagonal
        blocks[5][y*8+x] = (pixel)(40 + ((x + (y>>1)) * 12)); // shallow alt
        blocks[6][y*8+x] = ((x ^ y) & 1) ? 220 : 40;       // checkerboard
    }
    uint32_t s = 0x12345u;
    for (int i = 0; i < 64; i++) { s = s * 1103515245u + 12345u; blocks[7][i] = (pixel)(s >> 16); }

    printf("// AUTO-GENERATED by tools/extract_av1_cdef/harness.c — dav1d reference.\n");
    printf("// (best_dir, var) for each 8×8 input.\n");
    printf("pub(super) static CDEF_DIR_REF: &[(i32, u32)] = &[\n");
    for (int b = 0; b < 8; b++) {
        unsigned var = 0;
        int dir = cdef_find_dir_c(blocks[b], 8, &var);
        printf("    (%d, %u), // %s\n", dir, var, names[b]);
    }
    printf("];\n");
    return 0;
}
