//! End-to-end: an HTML document whose inline `<script>` mutates the DOM must
//! render the script-driven content into the PDF (no browser involved).
//!
//! Rendering text needs a real embedded font (the engine never bundles one).
//! These tests therefore load a TTF from the `GIGAPDF_TEST_FONT` environment
//! variable and **skip** when it is unset, so the suite stays hermetic. To run
//! them for real:
//!
//! ```bash
//! url=$(curl -s -H 'User-Agent: Mozilla/4.0' \
//!   'https://fonts.googleapis.com/css2?family=Roboto:wght@400' \
//!   | grep -oE 'https://[^)]+\.ttf' | head -1)
//! curl -s -o /tmp/roboto.ttf "$url"
//! GIGAPDF_TEST_FONT=/tmp/roboto.ttf cargo test -p gigapdf-core --test html_js
//! ```

use gigapdf_core::{html, Document};
use gigapdf_core::html::ProvidedFont;

fn test_font() -> Option<ProvidedFont> {
    let path = std::env::var("GIGAPDF_TEST_FONT").ok()?;
    let ttf = std::fs::read(path).ok()?;
    Some(ProvidedFont {
        family: "Roboto".to_string(),
        weight: 400,
        italic: false,
        ttf,
    })
}

fn page_text(pdf: &[u8]) -> String {
    let doc = Document::open(pdf).expect("open rendered PDF");
    doc.structured_text(1)
        .iter()
        .map(|l| l.text.clone())
        .collect::<Vec<_>>()
        .join(" ")
}

#[test]
fn script_generated_text_renders_into_pdf() {
    let Some(font) = test_font() else {
        eprintln!("skipped: set GIGAPDF_TEST_FONT to a .ttf to run this E2E test");
        return;
    };
    let src = "<html><body style=\"font-family: Roboto\">\
        <h1 id=\"t\">placeholder</h1>\
        <script>document.getElementById('t').textContent = 'Generated by JS';</script>\
        </body></html>";
    let pdf = html::render(src, &[font], 612.0, 792.0, 36.0);
    let text = page_text(&pdf);
    assert!(text.contains("Generated by JS"), "rendered text was: {text:?}");
    assert!(!text.contains("placeholder"), "stale text present: {text:?}");
}

#[test]
fn script_builds_a_list() {
    let Some(font) = test_font() else {
        eprintln!("skipped: set GIGAPDF_TEST_FONT to a .ttf to run this E2E test");
        return;
    };
    let src = "<html><body style=\"font-family: Roboto\"><ul id=\"list\"></ul><script>\
        var ul = document.getElementById('list');\
        ['Alpha', 'Beta', 'Gamma'].forEach(function(name){\
            var li = document.createElement('li');\
            li.textContent = name;\
            ul.appendChild(li);\
        });\
        </script></body></html>";
    let pdf = html::render(src, &[font], 612.0, 792.0, 36.0);
    let text = page_text(&pdf);
    for expected in ["Alpha", "Beta", "Gamma"] {
        assert!(text.contains(expected), "missing {expected:?} in {text:?}");
    }
}
