/* Reference vector generator: runs dav1d's real inverse 1D transforms on
 * deterministic inputs and prints results, to validate the Rust transcription
 * bit-for-bit. dav1d src/itx_1d.c (BSD-2-Clause). Dev-time only. */
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <assert.h>
#define NOINLINE
static inline int imin(int a,int b){return a<b?a:b;}
static inline int iclip(int v,int lo,int hi){return v<lo?lo:(v>hi?hi:v);}
/* Pull in the dav1d 1D transform bodies (functions are static). */
#define CLIP(a) iclip(a, min, max)
#include "itx_1d_body.c"

static void dump(const char*name,const int32_t*v,int n){
  printf("    // %s\n    &[",name);
  for(int i=0;i<n;i++){printf("%d%s",v[i],i+1<n?", ":"");}
  printf("],\n");
}
int main(void){
  /* Deterministic input vectors (length 64 max), reused per size. */
  int32_t base[64];
  for(int i=0;i<64;i++) base[i]=((i*37)%97)-48;   /* spread of +/- values */
  int mn=-32768, mx=32767;
  int32_t c[64];

  printf("// AUTO-GENERATED by tools/extract_av1_itx/harness.c — dav1d reference.\n");
  printf("pub(super) static ITX_REF: &[&[i32]] = &[\n");
  for(int i=0;i<4;i++)c[i]=base[i];  inv_dct4_1d_c(c,1,mn,mx);  dump("dct4",c,4);
  for(int i=0;i<8;i++)c[i]=base[i];  inv_dct8_1d_c(c,1,mn,mx);  dump("dct8",c,8);
  for(int i=0;i<16;i++)c[i]=base[i]; inv_dct16_1d_c(c,1,mn,mx); dump("dct16",c,16);
  for(int i=0;i<32;i++)c[i]=base[i]; inv_dct32_1d_c(c,1,mn,mx); dump("dct32",c,32);
  for(int i=0;i<4;i++)c[i]=base[i];  inv_adst4_1d_c(c,1,mn,mx);  dump("adst4",c,4);
  for(int i=0;i<8;i++)c[i]=base[i];  inv_adst8_1d_c(c,1,mn,mx);  dump("adst8",c,8);
  for(int i=0;i<16;i++)c[i]=base[i]; inv_adst16_1d_c(c,1,mn,mx); dump("adst16",c,16);
  for(int i=0;i<4;i++)c[i]=base[i];  inv_flipadst4_1d_c(c,1,mn,mx);  dump("flipadst4",c,4);
  for(int i=0;i<8;i++)c[i]=base[i];  inv_flipadst8_1d_c(c,1,mn,mx);  dump("flipadst8",c,8);
  for(int i=0;i<16;i++)c[i]=base[i]; inv_flipadst16_1d_c(c,1,mn,mx); dump("flipadst16",c,16);
  for(int i=0;i<4;i++)c[i]=base[i];  inv_identity4_1d_c(c,1,mn,mx);  dump("idt4",c,4);
  for(int i=0;i<8;i++)c[i]=base[i];  inv_identity8_1d_c(c,1,mn,mx);  dump("idt8",c,8);
  for(int i=0;i<16;i++)c[i]=base[i]; inv_identity16_1d_c(c,1,mn,mx); dump("idt16",c,16);
  for(int i=0;i<32;i++)c[i]=base[i]; inv_identity32_1d_c(c,1,mn,mx); dump("idt32",c,32);
  for(int i=0;i<4;i++)c[i]=base[i];  dav1d_inv_wht4_1d_c(c,1);       dump("wht4",c,4);
  for(int i=0;i<64;i++)c[i]=base[i]; inv_dct64_1d_c(c,1,mn,mx); dump("dct64",c,64);
  printf("];\n");
  return 0;
}
