#!/usr/bin/env python3
"""Regenerate a feature-baked `ocr_model_<group>.rs` from a `.gpocr` blob — the inverse of
`tools/ocr/gpocr.py` and the trainer's `emit_rust`. Use to bake a *chosen* trained variant
into its Cargo feature without retraining (e.g. after picking which of several trained
models ships as the feature-baked one).

The int8 weights are copied verbatim; f32 biases/scales are written at the same .7/.8
decimal precision `emit_rust` uses, so the output matches what training would have emitted
for that model. The format mirrors `LoadedModel::from_bytes` / `emit_rust` byte-for-byte.

Usage:  python3 tools/ocr/gpocr_to_rs.py models/ocr_alpha.gpocr alpha
        → writes crates/core/src/raster/ocr_model_alpha.rs
"""
from __future__ import annotations

import os
import struct
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


class _Cur:
    def __init__(self, b: bytes) -> None:
        self.b, self.o = b, 0

    def take(self, n: int) -> bytes:
        v = self.b[self.o : self.o + n]
        self.o += n
        return v

    def unpack(self, fmt: str):
        v = struct.unpack_from("<" + fmt, self.b, self.o)
        self.o += struct.calcsize("<" + fmt)
        return v


def parse(blob: bytes) -> dict:
    c = _Cur(blob)
    if c.take(4) != b"GPO1":
        raise ValueError("bad magic — not a .gpocr blob")
    (rtl,) = c.unpack("B")
    h, gru_in, gru_hid = c.unpack("HHH")
    (alen,) = c.unpack("I")
    alphabet = c.take(alen).decode("utf-8")
    (n_conv,) = c.unpack("B")
    convs = []
    for _ in range(n_conv):
        in_ch, out_ch, scale = c.unpack("HHf")
        w = list(c.unpack("%db" % (out_ch * in_ch * 9)))
        b = list(c.unpack("%df" % out_ch))
        convs.append((in_ch, out_ch, scale, w, b))
    grus = []
    for _ in range(2):
        w_scale, u_scale = c.unpack("ff")
        mats = [list(c.unpack("%db" % (gru_hid * gru_in))) for _ in range(3)]    # wz, wr, wn
        mats += [list(c.unpack("%db" % (gru_hid * gru_hid))) for _ in range(3)]  # uz, ur, un
        bvecs = [list(c.unpack("%df" % gru_hid)) for _ in range(3)]              # bz, br, bn
        grus.append((w_scale, u_scale, mats, bvecs))
    (fc_scale,) = c.unpack("f")
    fc_w = list(c.unpack("%db" % ((len(alphabet) + 1) * 2 * gru_hid)))
    fc_b = list(c.unpack("%df" % (len(alphabet) + 1)))
    return {"rtl": rtl, "h": h, "gru_in": gru_in, "gru_hid": gru_hid,
            "alphabet": alphabet, "convs": convs, "grus": grus, "fc": (fc_scale, fc_w, fc_b)}


def _i8(name: str, arr) -> str:
    return f"pub static {name}: [i8; {len(arr)}] = [{', '.join(str(int(v)) for v in arr)}];\n"


def _f32(name: str, arr) -> str:
    return f"pub static {name}: [f32; {len(arr)}] = [{', '.join(f'{v:.7}' for v in arr)}];\n"


def _gru(prefix: str, g) -> str:
    w_scale, u_scale, mats, bvecs = g
    out = "".join(_i8(f"{prefix}_{nm}", mats[i]) for i, nm in enumerate(("WZ", "WR", "WN", "UZ", "UR", "UN")))
    out += f"pub const {prefix}_W_SCALE: f32 = {w_scale:.8};\n"
    out += f"pub const {prefix}_U_SCALE: f32 = {u_scale:.8};\n"
    out += _f32(f"{prefix}_BZ", bvecs[0]) + _f32(f"{prefix}_BR", bvecs[1]) + _f32(f"{prefix}_BN", bvecs[2])
    return out


def _gru_ctor(prefix: str) -> str:
    return (
        f"GruSpec {{ wz: &{prefix}_WZ, wr: &{prefix}_WR, wn: &{prefix}_WN, "
        f"uz: &{prefix}_UZ, ur: &{prefix}_UR, un: &{prefix}_UN, "
        f"w_scale: {prefix}_W_SCALE, u_scale: {prefix}_U_SCALE, "
        f"bz: &{prefix}_BZ, br: &{prefix}_BR, bn: &{prefix}_BN }}"
    )


def emit_rust(group: str, m: dict) -> str:
    k = len(m["alphabet"])
    c1_in, c1_out, c1s, c1w, c1b = m["convs"][0]
    c2_in, c2_out, c2s, c2w, c2b = m["convs"][1]
    fc_scale, fc_w, fc_b = m["fc"]
    labels = m["alphabet"].replace("\\", "\\\\").replace('"', '\\"')
    return (
        f"//! AUTO-GENERATED by tools/ocr/gpocr_to_rs.py from models/ocr_{group}.gpocr — CRNN+CTC\n"
        f"//! line model, group '{group}'. int8-quantized; inference is the pure-`std` forward pass\n"
        f"//! in ocr_crnn.rs. {k} classes (+1 CTC blank). DO NOT EDIT — regenerate from the blob.\n"
        "#![allow(clippy::excessive_precision, clippy::unreadable_literal)]\n\n"
        "use super::ocr_crnn::{ConvSpec, Crnn, GruSpec};\n\n"
        f"pub const H: usize = {m['h']};\n"
        f"pub const GRU_IN: usize = {m['gru_in']};\n"
        f"pub const GRU_HID: usize = {m['gru_hid']};\n"
        f"pub const RTL: bool = {str(bool(m['rtl'])).lower()};\n"
        f'pub static ALPHABET: &str = "{labels}";\n\n'
        + _i8("C1_W", c1w) + _f32("C1_B", c1b) + f"pub const C1_SCALE: f32 = {c1s:.8};\n"
        + _i8("C2_W", c2w) + _f32("C2_B", c2b) + f"pub const C2_SCALE: f32 = {c2s:.8};\n\n"
        + _gru("FWD", m["grus"][0]) + "\n" + _gru("BWD", m["grus"][1]) + "\n"
        + _i8("FC_W", fc_w) + _f32("FC_B", fc_b) + f"pub const FC_SCALE: f32 = {fc_scale:.8};\n\n"
        "static CONV: [ConvSpec; 2] = [\n"
        f"    ConvSpec {{ w: &C1_W, scale: C1_SCALE, b: &C1_B, in_ch: {c1_in}, out_ch: {c1_out} }},\n"
        f"    ConvSpec {{ w: &C2_W, scale: C2_SCALE, b: &C2_B, in_ch: {c2_in}, out_ch: {c2_out} }},\n"
        "];\n\n"
        "/// The embedded model as a borrow the recognizer can run.\n"
        "pub(crate) fn model() -> Crnn<'static> {\n"
        "    Crnn {\n"
        "        h: H, conv: &CONV, gru_in: GRU_IN, gru_hid: GRU_HID,\n"
        f"        fwd: {_gru_ctor('FWD')},\n"
        f"        bwd: {_gru_ctor('BWD')},\n"
        "        fc_w: &FC_W, fc_scale: FC_SCALE, fc_b: &FC_B, alphabet: ALPHABET, rtl: RTL,\n"
        "    }\n"
        "}\n"
    )


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(f"usage: {argv[0]} <model.gpocr> <group>", file=sys.stderr)
        return 2
    blob_path, group = argv[1], argv[2]
    with open(blob_path, "rb") as f:
        model = parse(f.read())
    dest = os.path.join(ROOT, f"crates/core/src/raster/ocr_model_{group}.rs")
    with open(dest, "w", encoding="utf-8") as f:
        f.write(emit_rust(group, model))
    print(f"wrote {dest} ({os.path.getsize(dest) // 1024} KB) "
          f"[{len(model['alphabet'])} classes, {model['gru_in']}/{model['gru_hid']}, rtl={bool(model['rtl'])}]")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
