/* Reference generator for dav1d intra predictors (BSD-2-Clause). Sets a known
 * top/left/corner edge buffer, runs each predictor, dumps the WxH block as a
 * Rust array literal, to validate the Rust transcription bit-for-bit. */
#define BITDEPTH 8
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
typedef uint8_t pixel;
#define NOINLINE
static inline int imin(int a,int b){return a<b?a:b;}
static inline int imax(int a,int b){return a>b?a:b;}
static inline int iclip(int v,int lo,int hi){return v<lo?lo:(v>hi?hi:v);}
static inline int iclip_pixel(int v){return iclip(v,0,255);}
static inline int abs_i(int v){return v<0?-v:v;}
#define abs abs_i
static inline int apply_sign(int v,int s){return s<0?-v:v;}
static int ctz(unsigned x){int n=0;while(!(x&1)){x>>=1;n++;}return n;}
static void pixel_copy(pixel*d,const pixel*s,int n){for(int i=0;i<n;i++)d[i]=s[i];}
static void pixel_set(pixel*d,int v,int n){for(int i=0;i<n;i++)d[i]=(pixel)v;}
#define PXSTRIDE(x) (x)
#define HIGHBD_DECL_SUFFIX
#define HIGHBD_TAIL_SUFFIX
#define BASE_SHIFT 16
#define MULTIPLIER_1x2 0x5556
#define MULTIPLIER_1x4 0x3334
/* sm_weights table */
#include "smweights.c"
/* predictor bodies (extracted from ipred_tmpl.c) */
#include "dr_deriv.c"
#include "ipred_body.c"
#include "filter_body.c"

static void dump(const char*name,const pixel*b,int w,int h){
  printf("    // %s %dx%d\n    &[",name,w,h);
  for(int i=0;i<w*h;i++) printf("%d%s",b[i],i+1<w*h?", ":"");
  printf("],\n");
}
static void setedge(pixel*tl,int w,int h){
  tl[0]=100;
  for(int i=0;i<2*w;i++) tl[1+i]=(pixel)(130+i*3);   // top + topright extension
  for(int i=0;i<2*h;i++) tl[-(1+i)]=(pixel)(110-i*2);// left + bottomleft extension
}
int main(void){
  pixel buf[512]; pixel *tl=&buf[256];
  pixel out[64*64];
  printf("// AUTO-GENERATED by tools/extract_av1_ipred/harness.c — dav1d reference.\n");
  printf("pub(super) static IPRED_REF: &[&[i32]] = &[\n");
  int sizes[2]={4,8};
  for(int si=0;si<2;si++){int w=sizes[si],h=sizes[si];
    setedge(tl,w,h);
    ipred_dc_c(out,w,tl,w,h,0,0,0);        dump("dc",out,w,h);
    ipred_v_c(out,w,tl,w,h,0,0,0);         dump("v",out,w,h);
    ipred_h_c(out,w,tl,w,h,0,0,0);         dump("h",out,w,h);
    ipred_paeth_c(out,w,tl,w,h,0,0,0);     dump("paeth",out,w,h);
    ipred_smooth_c(out,w,tl,w,h,0,0,0);    dump("smooth",out,w,h);
    ipred_smooth_v_c(out,w,tl,w,h,0,0,0);  dump("smooth_v",out,w,h);
    ipred_smooth_h_c(out,w,tl,w,h,0,0,0);  dump("smooth_h",out,w,h);
    ipred_filter_c(out,w,tl,w,h,0,0,0); dump("filter0",out,w,h);
    ipred_filter_c(out,w,tl,w,h,1,0,0); dump("filter1",out,w,h);
    ipred_filter_c(out,w,tl,w,h,2,0,0); dump("filter2",out,w,h);
    ipred_filter_c(out,w,tl,w,h,3,0,0); dump("filter3",out,w,h);
    ipred_filter_c(out,w,tl,w,h,4,0,0); dump("filter4",out,w,h);
    ipred_z1_c(out,w,tl,w,h,1083,0,0); dump("z1a",out,w,h);
    ipred_z1_c(out,w,tl,w,h,1054,0,0); dump("z1b",out,w,h);
    ipred_z3_c(out,w,tl,w,h,1227,0,0); dump("z3a",out,w,h);
    ipred_z3_c(out,w,tl,w,h,1249,0,0); dump("z3b",out,w,h);
  }
  printf("];\n");
  return 0;
}
