/* Reference generator for the dav1d AV1 deblocking leaf filter (BSD-2-Clause).
 * Runs the real `loop_filter` on known p/q edge samples for each filter width +
 * threshold set, dumps the filtered buffers as Rust literals to validate the
 * Rust transcription bit-for-bit. dav1d src/loopfilter_tmpl.c. Dev-time only. */
#define BITDEPTH 8
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
typedef uint8_t pixel;
#define NOINLINE
#define HIGHBD_DECL_SUFFIX
#define HIGHBD_TAIL_SUFFIX
#define bitdepth_max 255
static inline int imin(int a, int b) { return a < b ? a : b; }
static inline int iclip(int v, int lo, int hi) { return v < lo ? lo : (v > hi ? hi : v); }
static inline int iclip_pixel(int v) { return iclip(v, 0, 255); }
static inline int abs_i(int v) { return v < 0 ? -v : v; }
#define abs abs_i
static inline int bitdepth_from_max(int m) { (void) m; return 8; }

#include "lf_body.c"

/* One edge spans 16 samples across; the edge sits between index 7 (p0) and 8
 * (q0). 4 lines stacked (stridea=16, strideb=1), `dst` at q0 of line 0. */
static void setline(pixel *b, const int *v) {
    for (int i = 0; i < 16; i++) b[i] = (pixel) v[i];
}
static void dump(const char *name, const pixel *buf) {
    printf("    // %s\n    &[", name);
    for (int i = 0; i < 64; i++) printf("%d%s", buf[i], i + 1 < 64 ? ", " : "");
    printf("],\n");
}

int main(void) {
    /* 4 lines exercising distinct paths: smooth ramp (flat8), sharp step
     * (narrow/hev), flat both sides, and a rough edge (fm may reject). */
    const int lines[4][16] = {
        { 30, 34, 38, 42, 46, 50, 54, 58, 92, 96, 100, 104, 108, 112, 116, 120 },
        { 40, 40, 40, 40, 40, 40, 40, 40, 200, 200, 200, 200, 200, 200, 200, 200 },
        { 70, 71, 72, 72, 73, 73, 74, 74, 78, 79, 79, 80, 81, 82, 82, 83 },
        { 10, 90, 20, 130, 60, 15, 200, 64, 70, 240, 12, 180, 33, 99, 5, 150 },
    };
    int widths[4] = { 4, 6, 8, 16 };
    /* (E, I, H) threshold sets — generous so filtering actually triggers. */
    int thr[3][3] = { { 64, 32, 16 }, { 255, 64, 8 }, { 120, 16, 4 } };

    printf("// AUTO-GENERATED by tools/extract_av1_lf/harness.c — dav1d reference.\n");
    printf("pub(super) static LF_REF: &[&[i32]] = &[\n");
    for (int wi = 0; wi < 4; wi++) {
        for (int ti = 0; ti < 3; ti++) {
            pixel buf[64];
            for (int l = 0; l < 4; l++) setline(&buf[l * 16], lines[l]);
            loop_filter(&buf[8], thr[ti][0], thr[ti][1], thr[ti][2], 16, 1, widths[wi]);
            char name[64];
            snprintf(name, sizeof name, "wd=%d E=%d I=%d H=%d", widths[wi], thr[ti][0], thr[ti][1], thr[ti][2]);
            dump(name, buf);
        }
    }
    printf("];\n");
    return 0;
}
